# Generated by Django 5.2.1 on 2026-04-30 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_blockchaintransaction_smartcontract_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='msme',
            name='assigned_bge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_msmes', to='portfolio.businessgrowthexpert'),
        ),
        migrations.CreateModel(
            name='BGEGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='bge_groups', to='portfolio.businessgrowthexpert')),
            ],
            options={
                'verbose_name': 'BGE Group',
                'verbose_name_plural': 'BGE Groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='msme',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msmes', to='portfolio.cohort'),
        ),
    ]
