# Generated by Django 5.2.1 on 2026-04-30 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_add_cohort_bgegroup_msme_assignments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessgrowthexpert',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked login account for this BGE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bge_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MSMEReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('initial', 'Initial Assessment'), ('followup', 'Follow-up Visit'), ('final', 'Final Assessment'), ('training', 'Training Support'), ('mentoring', 'Mentoring Session')], default='followup', max_length=20)),
                ('visit_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=10)),
                ('business_overview', models.TextField(blank=True, help_text='Brief overview of the business current state')),
                ('challenges_identified', models.TextField(blank=True, help_text='Key challenges observed during the visit')),
                ('support_provided', models.TextField(blank=True, help_text='Support and guidance provided during this visit')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for business improvement')),
                ('action_plan', models.TextField(blank=True, help_text='Agreed action plan with the MSME owner')),
                ('next_steps', models.TextField(blank=True, help_text='Next steps and follow-up actions')),
                ('additional_notes', models.TextField(blank=True, help_text='Any additional observations or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='portfolio.businessgrowthexpert')),
                ('msme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='portfolio.msme')),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
    ]
