# Generated by Django 5.2.1 on 2026-04-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_add_bge_user_link_and_msme_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessgrowthexpert',
            name='bge_code',
            field=models.CharField(blank=True, help_text='e.g. PRUDEV II-BGE-010T-7', max_length=50),
        ),
        migrations.AlterField(
            model_name='businessgrowthexpert',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
