# Generated by Django 5.2.1 on 2026-05-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_add_bge_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='msme',
            name='assignment_date',
            field=models.DateField(blank=True, help_text='Date this MSME was assigned to the BGE', null=True),
        ),
        migrations.AddField(
            model_name='msme',
            name='assignment_objectives',
            field=models.TextField(blank=True, help_text='Objectives and scope of this BGE deployment for the MSME'),
        ),
    ]
