# Generated by Django 5.2.1 on 2026-05-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_msme_assignment_objectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessgrowthexpert',
            name='deployment_objectives',
            field=models.TextField(blank=True, help_text='Shared objectives for this BGE across all their assigned MSMEs'),
        ),
    ]
