# Generated by Django 5.2.1 on 2026-05-08 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_push_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='msme',
            name='assigned_group',
            field=models.ForeignKey(blank=True, help_text='If set, every BGE in this group is considered assigned to this MSME.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_msmes', to='portfolio.bgegroup'),
        ),
        migrations.AddField(
            model_name='msme',
            name='session_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional session within a group rotation (e.g. Session 1, Session 2).', null=True),
        ),
    ]
