# Generated by Django 5.2.1 on 2026-05-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_msme_assigned_group_msme_session_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgegroup',
            name='objectives',
            field=models.TextField(blank=True, help_text='Mission statement for this group — flows into each assigned MSME and is visible to BGEs when they file reports.'),
        ),
    ]
