# Generated by Django 5.2.1 on 2026-05-09 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_bgegroup_objectives'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msmereport',
            options={},
        ),
        migrations.AddField(
            model_name='bgegroup',
            name='team_lead',
            field=models.ForeignKey(blank=True, help_text='Designated team lead. Only this BGE can file the group-level report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to='portfolio.businessgrowthexpert'),
        ),
        migrations.CreateModel(
            name='GroupReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveSmallIntegerField(blank=True, help_text='Optional rotation session this report covers.', null=True)),
                ('visit_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=10)),
                ('session_overview', models.TextField(blank=True, help_text='How the session ran, attendance, format.')),
                ('challenges_identified', models.TextField(blank=True, help_text='Cross-cutting challenges observed across the cohort.')),
                ('interventions_delivered', models.TextField(blank=True, help_text='Group-level interventions / training / coaching delivered.')),
                ('outcomes_achieved', models.TextField(blank=True, help_text='Quantitative + qualitative outcomes from the session.')),
                ('next_steps', models.TextField(blank=True, help_text='Follow-up plan agreed with the group.')),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='portfolio.bgegroup')),
                ('msmes_supported', models.ManyToManyField(blank=True, related_name='group_reports', to='portfolio.msme')),
                ('team_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_reports', to='portfolio.businessgrowthexpert')),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
    ]
