# Generated by Django 5.2.1 on 2026-05-10 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_alter_msmereport_options_bgegroup_team_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupreport',
            name='attendees',
            field=models.ManyToManyField(blank=True, help_text='Group members who attended this session.', related_name='attended_group_reports', to='portfolio.businessgrowthexpert'),
        ),
        migrations.CreateModel(
            name='GroupReportContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Member-level observations to feed into the consolidated group report.')),
                ('challenges_observed', models.TextField(blank=True)),
                ('interventions_made', models.TextField(blank=True)),
                ('follow_up_needed', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_contributions', to='portfolio.businessgrowthexpert')),
                ('group_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='portfolio.groupreport')),
                ('msmes_observed', models.ManyToManyField(blank=True, related_name='group_contributions', to='portfolio.msme')),
            ],
            options={
                'verbose_name': 'Group Report Contribution',
                'ordering': ['-updated_at'],
                'unique_together': {('group_report', 'bge')},
            },
        ),
    ]
