# Generated by Django 5.2.1 on 2026-05-11 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_groupreport_attendees_groupreportcontribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('work_order_type', models.CharField(choices=[('msme_support', 'MSME CRM & Business Support'), ('mobilisation', 'Mobilisation / Outreach'), ('group_session', 'Peer-to-Peer Group Session'), ('other', 'Other')], default='msme_support', max_length=30)),
                ('project_name', models.CharField(default='Promoting Rural Development II (PRUDEV II)', max_length=200)),
                ('issue_date', models.DateField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='Northern Uganda (Gulu & Lira)', max_length=200)),
                ('duration', models.CharField(blank=True, default='2 months', max_length=100)),
                ('objective', models.TextField(blank=True)),
                ('key_tasks', models.TextField(blank=True, help_text='One task per line.')),
                ('deliverables_json', models.JSONField(blank=True, default=list)),
                ('rate_per_day', models.PositiveIntegerField(default=60000)),
                ('max_days', models.PositiveSmallIntegerField(default=4)),
                ('transport_reimbursed', models.BooleanField(default=True)),
                ('payment_notes', models.TextField(blank=True)),
                ('team_leader_name', models.CharField(default='Stephen Maxi Opwonya', max_length=200)),
                ('team_leader_position', models.CharField(default='Team Leader', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('signed', 'Signed')], default='draft', max_length=20)),
                ('bge_signed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='portfolio.businessgrowthexpert')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='portfolio.bgegroup')),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
    ]
