# Generated by Django 5.2.1 on 2026-05-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_work_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessgrowthexpert',
            name='signature',
            field=models.ImageField(blank=True, help_text='JPEG/PNG signature image; background will be normalised on upload', null=True, upload_to='signatures/'),
        ),
    ]
