# Generated by Django 5.2.1 on 2026-05-11 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_bge_signature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['session', 'attendee_name']},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='age_group',
            field=models.CharField(blank=True, choices=[('18-34', '18–34 (Youth)'), ('35-45', '35–45'), ('46-55', '46–55'), ('56+', '56+')], max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendee_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendee_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='attendance',
            name='consent_contact',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='consent_photo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AddField(
            model_name='attendance',
            name='refugee_status',
            field=models.CharField(blank=True, choices=[('R', 'Refugee'), ('H', 'Host Community')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='msme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='portfolio.msme'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.BooleanField(default=True),
        ),
    ]
