# Generated by Django 5.2.1 on 2026-05-11 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_attendance_demographics'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='Optional: link this session to a BGE deployment/work order for reporting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to='portfolio.workorder'),
        ),
    ]
