# Generated by Django 5.2.1 on 2026-05-11 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_session_work_order_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupReportAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_name', models.CharField(blank=True, max_length=200)),
                ('attendee_phone', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age_group', models.CharField(blank=True, choices=[('18-34', '18–34 (Youth)'), ('35-45', '35–45'), ('46-55', '46–55'), ('56+', '56+')], max_length=10)),
                ('refugee_status', models.CharField(blank=True, choices=[('R', 'Refugee'), ('H', 'Host Community')], default='H', max_length=1)),
                ('consent_photo', models.BooleanField(default=True)),
                ('consent_contact', models.BooleanField(default=True)),
                ('group_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msme_attendance', to='portfolio.groupreport')),
                ('msme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_report_attendances', to='portfolio.msme')),
            ],
            options={
                'ordering': ['group_report', 'attendee_name'],
            },
        ),
    ]
