# Generated by Django 5.2.1 on 2026-05-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_group_report_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupreport',
            name='submitted_pdf',
            field=models.FileField(blank=True, null=True, upload_to='group_reports/submitted/'),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='submitted_pdf',
            field=models.FileField(blank=True, null=True, upload_to='reports/submitted/'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='signed_pdf',
            field=models.FileField(blank=True, null=True, upload_to='work_orders/signed/'),
        ),
    ]
