# Generated by Django 5.2.1 on 2026-05-12 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0031_stored_pdf_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managed_cohorts', models.ManyToManyField(blank=True, help_text='Cohorts this programme manager can see and manage.', related_name='cohort_admins', to='portfolio.cohort')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programme Manager',
                'verbose_name_plural': 'Programme Managers',
            },
        ),
    ]
