# Generated by Django 5.2.1 on 2026-05-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_cohort_admin_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, default='#1A2F4B', help_text='Hex colour used for the chip in the UI (e.g. #2E7D32).', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Programme Group',
                'verbose_name_plural': 'Programme Groups',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='cohortadmin',
            name='managed_cohorts',
        ),
        migrations.AddField(
            model_name='cohortadmin',
            name='managed_groups',
            field=models.ManyToManyField(blank=True, help_text='Programme groups this manager can see and manage.', related_name='managers', to='portfolio.programmegroup'),
        ),
        migrations.AddField(
            model_name='msme',
            name='programme_groups',
            field=models.ManyToManyField(blank=True, help_text='Cross-cutting programme labels (e.g. Green MSMEs, Agroprocessors).', related_name='msmes', to='portfolio.programmegroup'),
        ),
    ]
