# Generated by Django 5.2.1 on 2026-05-12 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_seed_programme_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='msme',
            name='diag_annual_turnover',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total sales/turnover in last 12 months (UGX) from diagnostic tool', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='msme',
            name='diag_district',
            field=models.CharField(blank=True, help_text='District from diagnostic tool (District_clean column)', max_length=100),
        ),
        migrations.AddField(
            model_name='msme',
            name='diag_employees_ft_female',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Full-time female employees at diagnostic baseline', null=True),
        ),
        migrations.AddField(
            model_name='msme',
            name='diag_employees_ft_male',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Full-time male employees at diagnostic baseline', null=True),
        ),
        migrations.AddField(
            model_name='msme',
            name='diag_employees_pt_female',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Part-time female employees at diagnostic baseline', null=True),
        ),
        migrations.AddField(
            model_name='msme',
            name='diag_employees_pt_male',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Part-time male employees at diagnostic baseline', null=True),
        ),
        migrations.AddField(
            model_name='msme',
            name='diag_green_categories',
            field=models.JSONField(blank=True, default=list, help_text='List of green business categories the MSME falls into'),
        ),
        migrations.AddField(
            model_name='msme',
            name='diag_has_business_bank',
            field=models.BooleanField(blank=True, help_text='Has a business bank account', null=True),
        ),
        migrations.AddField(
            model_name='msme',
            name='diag_has_mobile_money',
            field=models.BooleanField(blank=True, help_text='Has a mobile money account', null=True),
        ),
        migrations.AddField(
            model_name='msme',
            name='diag_has_tin',
            field=models.BooleanField(blank=True, help_text='Has a Tax Identification Number (TIN)', null=True),
        ),
        migrations.AddField(
            model_name='msme',
            name='diag_has_unbs',
            field=models.BooleanField(blank=True, help_text='Has products registered with Uganda National Bureau of Standards', null=True),
        ),
        migrations.AddField(
            model_name='msme',
            name='diag_imported_at',
            field=models.DateTimeField(blank=True, help_text='When the diagnostic baseline was imported', null=True),
        ),
        migrations.AddField(
            model_name='msme',
            name='diag_is_green_business',
            field=models.BooleanField(blank=True, help_text='Falls into at least one green business category', null=True),
        ),
        migrations.AddField(
            model_name='msme',
            name='diag_owner_age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Owner age at time of diagnostic', null=True),
        ),
        migrations.AddField(
            model_name='msme',
            name='diag_owner_education',
            field=models.CharField(blank=True, help_text='Owner education level from diagnostic tool', max_length=100),
        ),
        migrations.AddField(
            model_name='msme',
            name='diag_owner_sex',
            field=models.CharField(blank=True, help_text='Owner sex as reported in diagnostic tool', max_length=20),
        ),
        migrations.AddField(
            model_name='msme',
            name='diag_total_assets',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Investment in total assets (UGX) from diagnostic tool', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='msme',
            name='diag_years_operating',
            field=models.CharField(blank=True, help_text='How long the business has been operating (as reported)', max_length=50),
        ),
        migrations.CreateModel(
            name='MSMEGrowthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('source', models.CharField(choices=[('diagnostic', 'Application Diagnostic (Baseline)'), ('bge_visit', 'BGE Visit'), ('quarterly', 'Quarterly Review'), ('annual', 'Annual Review'), ('other', 'Other')], default='bge_visit', max_length=20)),
                ('annual_turnover', models.DecimalField(blank=True, decimal_places=2, help_text='Total sales/turnover in last 12 months (UGX)', max_digits=18, null=True)),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, help_text='Investment in total assets (UGX)', max_digits=18, null=True)),
                ('employees_ft_male', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('employees_ft_female', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('employees_pt_male', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('employees_pt_female', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('has_tin', models.BooleanField(blank=True, null=True)),
                ('has_unbs', models.BooleanField(blank=True, null=True)),
                ('has_business_bank', models.BooleanField(blank=True, null=True)),
                ('has_mobile_money', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(blank=True, help_text='BGE who collected this data (leave blank for imported baselines)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_snapshots', to='portfolio.businessgrowthexpert')),
                ('msme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_snapshots', to='portfolio.msme')),
            ],
            options={
                'verbose_name': 'Growth Snapshot',
                'verbose_name_plural': 'Growth Snapshots',
                'ordering': ['msme', 'snapshot_date'],
            },
        ),
    ]
