# Generated by Django 5.2.1 on 2026-05-12 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0037_binary_signature_and_signed_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('include_financials', models.BooleanField(default=True, help_text='Revenue, profit, total assets')),
                ('include_workforce', models.BooleanField(default=True, help_text='FT/PT employee counts by gender')),
                ('include_compliance', models.BooleanField(default=True, help_text='TIN, UNBS, bank, mobile money, NSSF')),
                ('include_market', models.BooleanField(default=False, help_text='Customer base, exporting, new products')),
                ('include_business_mgmt', models.BooleanField(default=False, help_text='Business plan, digital accounting, HR policy')),
                ('include_growth_rating', models.BooleanField(default=True, help_text='BGE 1-5 growth score + key achievement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='msmereport',
            name='accepts_digital_payments',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='active_customers_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='employees_ft_female',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='employees_ft_male',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='employees_pt_female',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='employees_pt_male',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='growth_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='BGE growth assessment score 1–5', null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='has_business_bank',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='has_business_plan',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='has_hr_policy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='has_mobile_money',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='has_nssf',
            field=models.BooleanField(blank=True, help_text='Making NSSF contributions', null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='has_tin',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='has_unbs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='introduced_new_product',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='is_exporting',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='key_achievement',
            field=models.TextField(blank=True, help_text='Main growth achievement since last visit'),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='monthly_profit_ugx',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average monthly profit (UGX)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='revenue_ugx',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total sales/turnover last 12 months (UGX)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='submitted_pdf_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='total_assets_ugx',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total business assets (UGX)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='uses_digital_accounting',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='msmereport',
            name='action_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='msmereport',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='msmereport',
            name='business_overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='msmereport',
            name='challenges_identified',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='msmereport',
            name='next_steps',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='msmereport',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='msmereport',
            name='support_provided',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Report template chosen at visit time', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='portfolio.visitreporttemplate'),
        ),
    ]
