# Generated by Django 5.2.1 on 2026-05-13 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0043_bge_is_senior_and_facilitation_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('training_title', models.CharField(blank=True, max_length=300)),
                ('training_dates', models.CharField(blank=True, help_text='e.g. "17–19 February 2026"', max_length=100)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('time_allocation', models.CharField(blank=True, help_text='e.g. "2 hours" or "3 days"', max_length=100)),
                ('facilitation_team', models.TextField(blank=True, help_text='Names of co-facilitators, guest trainers, etc.')),
                ('participants_male_youth', models.PositiveIntegerField(default=0, help_text='Male, age 15–35')),
                ('participants_female_youth', models.PositiveIntegerField(default=0, help_text='Female, age 15–35')),
                ('participants_adult_male', models.PositiveIntegerField(default=0, help_text='Male, age 36+')),
                ('participants_adult_female', models.PositiveIntegerField(default=0, help_text='Female, age 36+')),
                ('training_purpose', models.TextField(blank=True, help_text='Background and purpose of the session')),
                ('session_objectives', models.TextField(blank=True, help_text='What was the objective of the session?')),
                ('activities_delivered', models.TextField(blank=True, help_text='What activities/tasks were delivered?')),
                ('key_lessons', models.TextField(blank=True, help_text='What key lessons were learnt?')),
                ('growth_support_areas', models.TextField(blank=True, help_text='What growth support areas were observed?')),
                ('key_findings', models.TextField(blank=True, help_text='Key findings and critical issues from the session')),
                ('bge_contributions', models.TextField(blank=True, help_text='BGE contributions and development needs observed')),
                ('bds_actions', models.TextField(blank=True, help_text='What BDS actions would you propose for the next 3 months?')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for future sessions')),
                ('next_steps', models.TextField(blank=True, help_text='Agreed next steps')),
                ('conclusion', models.TextField(blank=True, help_text='Summary conclusion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('bge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_reports', to='portfolio.businessgrowthexpert')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_report', to='portfolio.trainingsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
