# Generated by Django 5.2.1 on 2026-05-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0046_workorder_type_msme_finance_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='msmegrowthsnapshot',
            name='employees_ft_refugee',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Full-time staff who are refugees', null=True),
        ),
        migrations.AddField(
            model_name='msmegrowthsnapshot',
            name='employees_pt_refugee',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Part-time staff who are refugees', null=True),
        ),
        migrations.AddField(
            model_name='msmegrowthsnapshot',
            name='momo_pay_code',
            field=models.CharField(blank=True, default='', help_text='MTN/Airtel MOMO Pay merchant code', max_length=50),
        ),
    ]
