# Generated by Django 5.2.1 on 2026-05-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0047_growth_snapshot_momo_refugee_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='msmegrowthsnapshot',
            name='has_momo_pay',
            field=models.BooleanField(blank=True, help_text='Business has a MOMO Pay merchant code', null=True),
        ),
    ]
