# Generated by Django 5.2.1 on 2026-05-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0050_visitreport_rename_has_unbs_to_has_ursb'),
    ]

    operations = [
        migrations.AddField(
            model_name='msmegrowthsnapshot',
            name='digital_tools',
            field=models.JSONField(blank=True, default=list, help_text='Digital tools the business has adopted (list of strings)'),
        ),
        migrations.AddField(
            model_name='msmegrowthsnapshot',
            name='digital_tools_other',
            field=models.CharField(blank=True, default='', help_text='Other digital tools not in the standard list', max_length=300),
        ),
        migrations.AddField(
            model_name='msmegrowthsnapshot',
            name='training_changes',
            field=models.JSONField(blank=True, default=list, help_text='Areas where training has led to changes (list of strings)'),
        ),
        migrations.AddField(
            model_name='msmegrowthsnapshot',
            name='training_changes_other',
            field=models.CharField(blank=True, default='', help_text='Other training-driven changes not in the standard list', max_length=500),
        ),
        migrations.AddField(
            model_name='msmegrowthsnapshot',
            name='training_made_changes',
            field=models.BooleanField(blank=True, help_text='Has training delivered by the programme made changes to the business?', null=True),
        ),
        migrations.AlterField(
            model_name='msmegrowthsnapshot',
            name='has_ursb',
            field=models.BooleanField(blank=True, help_text='Registered with Uganda Registration Services Bureau', null=True),
        ),
    ]
