# Generated by Django 5.2.1 on 2026-05-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0051_growth_snapshot_digital_tools_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='msmereport',
            name='markets_outside_district',
            field=models.BooleanField(blank=True, help_text='Does the MSME access markets outside their district of operation?', null=True),
        ),
    ]
