# Generated by Django 5.2.1 on 2026-05-18 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0053_msme_report_annual_review_visit_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupreport',
            options={'ordering': ['-visit_date', '-created_at'], 'verbose_name': 'Group Report'},
        ),
        migrations.CreateModel(
            name='AnnualReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_period', models.CharField(choices=[('annual', 'Annual Review'), ('quarterly', 'Quarterly Review'), ('midterm', 'Mid-term Review')], default='annual', max_length=20)),
                ('review_date', models.DateField(help_text='Date the review session was conducted.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=10)),
                ('session_overview', models.TextField(blank=True, help_text='How the review session ran — format, attendance, general atmosphere.')),
                ('key_achievements', models.TextField(blank=True, help_text='Notable progress or milestones observed across the reviewed MSMEs.')),
                ('challenges_identified', models.TextField(blank=True, help_text='Common or individual challenges observed.')),
                ('support_provided', models.TextField(blank=True, help_text='Coaching, advice, or resources provided during the review.')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations to the programme or individual MSMEs.')),
                ('next_steps', models.TextField(blank=True, help_text='Agreed follow-up actions.')),
                ('additional_notes', models.TextField(blank=True)),
                ('submitted_pdf_data', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('bge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_review_reports', to='portfolio.businessgrowthexpert')),
                ('msmes_reviewed', models.ManyToManyField(blank=True, help_text='MSMEs included in this review session.', related_name='annual_review_reports', to='portfolio.msme')),
            ],
            options={
                'verbose_name': 'Annual Review Report',
                'ordering': ['-review_date', '-created_at'],
            },
        ),
    ]
