# Generated by Django 5.2.1 on 2026-05-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0054_annual_review_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='msmereport',
            name='coaching_focus_area',
            field=models.CharField(blank=True, help_text='Focus area for coaching visits', max_length=100),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='delivery_method',
            field=models.CharField(blank=True, help_text='Training delivery method (training visits)', max_length=60),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='participant_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of participants (training visits)', null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='tools_provided',
            field=models.TextField(blank=True, help_text='Comma-separated tools, templates or materials given'),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='visit_objectives',
            field=models.TextField(blank=True, help_text='What this visit aimed to achieve'),
        ),
        migrations.AlterField(
            model_name='msmereport',
            name='action_plan',
            field=models.TextField(blank=True, help_text='MSME agreed actions / assignments given'),
        ),
        migrations.AlterField(
            model_name='msmereport',
            name='business_overview',
            field=models.TextField(blank=True, help_text='Context observed / topics covered / what was discussed'),
        ),
        migrations.AlterField(
            model_name='msmereport',
            name='challenges_identified',
            field=models.TextField(blank=True, help_text='Challenges encountered or observed'),
        ),
        migrations.AlterField(
            model_name='msmereport',
            name='key_achievement',
            field=models.TextField(blank=True, help_text='Key outcomes, takeaways or owner insights'),
        ),
        migrations.AlterField(
            model_name='msmereport',
            name='recommendations',
            field=models.TextField(blank=True, help_text='BGE follow-up actions / next session plan'),
        ),
        migrations.AlterField(
            model_name='msmereport',
            name='support_provided',
            field=models.TextField(blank=True, help_text='Support, coaching, or training content delivered'),
        ),
        migrations.AlterField(
            model_name='msmereport',
            name='visit_type',
            field=models.CharField(choices=[('one_on_one', 'One-on-One Visit'), ('training', 'Training Visit'), ('coaching', 'Business Coaching Visit'), ('initial', 'Initial Assessment'), ('followup', 'Follow-up Visit'), ('final', 'Final Assessment'), ('mentoring', 'Mentoring Session'), ('annual_review', 'Annual Review'), ('quarterly_review', 'Quarterly Review')], default='followup', max_length=20),
        ),
    ]
