# Generated by Django 5.2.1 on 2026-05-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0057_workorder_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='lead_bge',
            field=models.ForeignKey(blank=True, help_text='Senior BGE co-facilitating/leading this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_sessions', to='portfolio.businessgrowthexpert'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='mentor_bges',
            field=models.ManyToManyField(blank=True, help_text='Regular BGEs attending as mentors', related_name='mentor_sessions', to='portfolio.businessgrowthexpert'),
        ),
        migrations.CreateModel(
            name='MentorTrainingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('training_title', models.CharField(blank=True, max_length=300)),
                ('training_dates', models.CharField(blank=True, max_length=100)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('mentoring_activities', models.TextField(blank=True, help_text='Activities carried out as a mentor')),
                ('msmes_mentored', models.TextField(blank=True, help_text='MSMEs specifically supported during session')),
                ('key_observations', models.TextField(blank=True, help_text='Key observations on MSME progress/needs')),
                ('challenges', models.TextField(blank=True, help_text='Challenges encountered during mentoring')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for future sessions')),
                ('next_steps', models.TextField(blank=True, help_text='Agreed follow-up actions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('bge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_reports', to='portfolio.businessgrowthexpert')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_reports', to='portfolio.trainingsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('session', 'bge')},
            },
        ),
    ]
