# Generated by Django 5.2.1 on 2026-05-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0058_mentor_training_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='mentor_work_orders',
            field=models.ManyToManyField(blank=True, help_text='Work orders for each mentor BGE in this session', related_name='mentor_training_sessions', to='portfolio.workorder'),
        ),
    ]
