# Generated by Django 5.2.1 on 2026-05-19 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0061_consolidate_facilitation_assignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingfacilitationassignment',
            options={'ordering': ['topic__module_number', 'topic__section_number', 'bge__name', 'id']},
        ),
        migrations.AlterField(
            model_name='trainingfacilitationassignment',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilitation_assignments', to='portfolio.trainingtopic'),
        ),
    ]
