# Generated by Django 5.2.1 on 2026-05-22 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0062_make_facilitation_topic_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='msmegrowthsnapshot',
            name='source',
            field=models.CharField(choices=[('diagnostic', 'Application Diagnostic (Baseline)'), ('bge_visit', 'BGE Visit'), ('quarterly', 'Quarterly Review'), ('annual', 'Data Update'), ('other', 'Other')], default='bge_visit', max_length=20),
        ),
        migrations.CreateModel(
            name='TshirtReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='T-Shirt Collection Receipt', max_length=200)),
                ('event', models.CharField(blank=True, max_length=200)),
                ('colour', models.CharField(default='Blue', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tshirt_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TshirtReceiptEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('L', 'L'), ('XL', 'XL'), ('2XL', '2XL')], default='L', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('bge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tshirt_entries', to='portfolio.businessgrowthexpert')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='portfolio.tshirtreceipt')),
            ],
            options={
                'ordering': ['order', 'bge__name'],
                'unique_together': {('receipt', 'bge')},
            },
        ),
    ]
