# Generated by Django 5.2.1 on 2026-05-30 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0063_tshirt_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('bge', 'BGE Expert'), ('msme', 'MSME')], max_length=10)),
                ('recipient_id', models.PositiveIntegerField()),
                ('recipient_phone', models.CharField(max_length=30)),
                ('message_preview', models.CharField(max_length=160)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['recipient_type', 'recipient_id'], name='portfolio_s_recipie_3673f4_idx')],
            },
        ),
    ]
