# Generated by Django 5.2.1 on 2026-06-04 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0064_add_sms_send_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='work_order_type',
            field=models.CharField(choices=[('msme_support', 'MSME CRM & Business Support'), ('msme_data_update', 'MSME Data Update & Verification'), ('msme_finance_survey', 'MSME Finance Survey (Google Forms)'), ('msme_access_finance', 'Access to Finance & Digital Onboarding'), ('biz_continuity', 'Business Continuity & Operational Planning'), ('mobilisation', 'Mobilisation / Outreach'), ('group_session', 'Peer-to-Peer Group Session'), ('training_facilitation', 'Training Facilitation — Senior BGE'), ('other', 'Other')], default='msme_support', max_length=30),
        ),
        migrations.CreateModel(
            name='UserSecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_change_password', models.BooleanField(default=True, help_text='Force password change on next login (set on account creation).')),
                ('password_last_changed', models.DateTimeField(blank=True, help_text='Set whenever the user successfully changes their password.', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Security Profile',
            },
        ),
    ]
