# Generated by Django 5.2.1 on 2026-06-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0065_add_user_security_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='co_bges',
            field=models.ManyToManyField(blank=True, help_text='Other BGEs jointly deployed with this work order (for collaboration emails).', related_name='co_deployed_work_orders', to='portfolio.businessgrowthexpert'),
        ),
    ]
