# Generated by Django 5.2.1 on 2026-06-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0066_add_work_order_co_bges'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='msme_ids_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
