# Generated by Django 5.2.1 on 2026-06-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0067_add_work_order_msme_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='msme',
            name='co_assigned_bges',
            field=models.ManyToManyField(blank=True, help_text='Additional BGEs who are also deployed to this MSME alongside the primary BGE.', related_name='co_assigned_msmes', to='portfolio.businessgrowthexpert'),
        ),
    ]
