# Generated by Django 5.2.1 on 2026-06-11 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0068_add_msme_co_assigned_bges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecurityprofile',
            name='viewer_approved',
            field=models.BooleanField(default=True, help_text='False = account is pending admin approval and has no data access. Set to False automatically for Google sign-ins outside the allowed domain list that could not be linked to a BGE/programme-manager profile.'),
        ),
        migrations.CreateModel(
            name='WorkOrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('reference', models.CharField(blank=True, help_text='Bank/mobile money transaction reference, cheque number, etc.', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_work_order_payments', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='portfolio.workorder')),
            ],
            options={
                'verbose_name': 'Work Order Payment',
                'verbose_name_plural': 'Work Order Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timesheet_file', models.FileField(blank=True, null=True, upload_to='work_orders/timesheets/')),
                ('timesheet_data', models.BinaryField(blank=True, null=True)),
                ('timesheet_filename', models.CharField(blank=True, max_length=255)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='work_orders/invoices/')),
                ('invoice_data', models.BinaryField(blank=True, null=True)),
                ('invoice_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_order_submissions', to='portfolio.businessgrowthexpert')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_submissions', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='portfolio.workorder')),
            ],
            options={
                'verbose_name': 'Timesheet & Invoice Submission',
                'verbose_name_plural': 'Timesheet & Invoice Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
