# Generated by Django 5.2.1 on 2026-06-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0069_usersecurityprofile_viewer_approved_workorderpayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderpayment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorderpayment',
            name='confirmed_by_bge',
            field=models.BooleanField(default=False, help_text='True once the BGE has confirmed receipt of this payment.'),
        ),
        migrations.AddField(
            model_name='workorderpayment',
            name='notified_at',
            field=models.DateTimeField(blank=True, help_text='When the BGE was last emailed about this payment.', null=True),
        ),
    ]
