# Generated by Django 5.2.1 on 2026-06-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0070_workorderpayment_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecurityprofile',
            name='email_verified',
            field=models.BooleanField(default=True, help_text='False = account was created with an unverified email and cannot log in until the user clicks the verification link sent to their inbox. Defaults to True for accounts that pre-date this feature and for Google sign-ins (Google already verifies the email address).'),
        ),
    ]
