# Generated by Django 5.2.1 on 2026-06-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0070_workorderpayment_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderpayment',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Remaining balance on the invoice after this payment.', max_digits=12, null=True),
        ),
    ]
