# Generated by Django 5.2.1 on 2026-06-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0070_workorderpayment_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessgrowthexpert',
            name='allow_concurrent_work_orders',
            field=models.BooleanField(default=False, help_text='Allow this BGE to have multiple work orders with overlapping date ranges.'),
        ),
    ]
