# Generated by Django 5.2.1 on 2026-07-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0074_remove_usersecurityprofile_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='work_order_type',
            field=models.CharField(choices=[('msme_support', 'MSME CRM & Business Support'), ('msme_data_update', 'MSME Data Update & Verification'), ('msme_finance_survey', 'MSME Finance Survey (Google Forms)'), ('msme_access_finance', 'Access to Finance & Digital Onboarding'), ('access_to_finance_bge', 'Access to Finance — BGE Template'), ('biz_continuity', 'Business Continuity & Operational Planning'), ('biz_continuity_workshop', 'Business Continuity — Workshop Design & Facilitation'), ('mobilisation', 'Mobilisation / Outreach'), ('group_session', 'Peer-to-Peer Group Session'), ('training_facilitation', 'Training Facilitation — Senior BGE'), ('outcome_assessment_tool', 'Outcome Assessment Tool Delivery'), ('other', 'Other')], default='msme_support', max_length=30),
        ),
    ]
