# Generated by Django 5.2.1 on 2026-07-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0077_work_order_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='body_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
