# Generated by Django 5.2.1 on 2026-07-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0078_scheduled_message_body_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='msme',
            name='co_assignment_objectives',
            field=models.JSONField(blank=True, default=dict, help_text='Per-co-assignee objectives keyed by BGE id string, e.g. {"5": "Sales support"}'),
        ),
    ]
