# Generated by Django 5.2.1 on 2026-07-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0081_create_viewer_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='participant_bges',
            field=models.ManyToManyField(blank=True, help_text='BGEs attending as participants in a BCP Tool Training session.', related_name='bcp_participant_work_orders', to='portfolio.businessgrowthexpert'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_order_type',
            field=models.CharField(choices=[('msme_support', 'MSME CRM & Business Support'), ('msme_data_update', 'MSME Data Update & Verification'), ('msme_finance_survey', 'MSME Finance Survey (Google Forms)'), ('msme_access_finance', 'Access to Finance & Digital Onboarding'), ('access_to_finance_bge', 'Access to Finance — BGE Template'), ('biz_continuity', 'Business Continuity & Operational Planning'), ('biz_continuity_workshop', 'Business Continuity — Workshop Design & Facilitation'), ('agro_biz_continuity', 'Agro-processors — Business Continuity & Strategic Planning'), ('mobilisation', 'Mobilisation / Outreach'), ('group_session', 'Peer-to-Peer Group Session'), ('training_facilitation', 'Training Facilitation — Senior BGE'), ('bcp_tool_facilitation', 'BCP Tool Training — Senior BGE Facilitator'), ('bcp_tool_training', 'BCP Tool Training — BGE Participant'), ('outcome_assessment_tool', 'Outcome Assessment Tool Delivery'), ('other', 'Other')], default='msme_support', max_length=30),
        ),
    ]
