# Generated by Django 5.2.1 on 2026-07-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0082_add_participant_bges_to_workorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='bge_participants',
            field=models.ManyToManyField(blank=True, related_name='sessions_attended_as_participant', to='portfolio.businessgrowthexpert'),
        ),
    ]
