# Generated by Django 5.2.1 on 2026-08-01 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0087_msme_search_gin_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGEParticipantTrainingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('training_title', models.CharField(blank=True, max_length=300)),
                ('training_dates', models.CharField(blank=True, help_text='e.g. "17–19 February 2026"', max_length=100)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('facilitator_name', models.CharField(blank=True, max_length=200)),
                ('topics_covered', models.TextField(blank=True, help_text='Topics/modules covered in the training')),
                ('key_learnings', models.TextField(blank=True, help_text='Key lessons and insights from the training')),
                ('practical_application', models.TextField(blank=True, help_text='How will you apply these learnings with your MSMEs?')),
                ('msmes_as_test_subjects', models.TextField(blank=True, help_text='MSMEs used as practice subjects during the training')),
                ('challenges', models.TextField(blank=True, help_text='Challenges encountered during the training')),
                ('action_plan', models.TextField(blank=True, help_text='Planned next steps and follow-up actions')),
                ('attendees', models.JSONField(blank=True, default=list, help_text='Attendance register of BGE participants in the training')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='msme',
            name='msme_business_name_gin',
        ),
        migrations.RemoveIndex(
            model_name='msme',
            name='msme_owner_name_gin',
        ),
        migrations.RemoveIndex(
            model_name='msme',
            name='msme_code_gin',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_order_type',
            field=models.CharField(choices=[('msme_support', 'MSME CRM & Business Support'), ('msme_data_update', 'MSME Data Update & Verification'), ('msme_finance_survey', 'MSME Finance Survey (Google Forms)'), ('msme_access_finance', 'Access to Finance & Digital Onboarding'), ('access_to_finance_bge', 'Access to Finance — BGE Template'), ('agro_biz_continuity', 'Agro-processors — Business Continuity & Strategic Planning'), ('bcp_senior_facilitator', 'Agro-processors BCP — Senior BGE Lead Facilitator'), ('mobilisation', 'Mobilisation / Outreach'), ('group_session', 'Peer-to-Peer Group Session'), ('bcp_tool_training', 'BCP Tool Training — BGE Participant'), ('bge_bcp_participant_mentor', 'Agro-processors — Business Continuity & Strategic Planning (BGE Support)'), ('outcome_assessment_tool', 'Outcome Assessment Tool Delivery'), ('fi_mobilisation_bcp', 'BCP Tool - Field Implementation'), ('carbon_emissions_training', 'Carbon Emissions Measurement Framework — Training & Field Implementation'), ('other', 'Other')], default='msme_support', max_length=30),
        ),
        migrations.AddField(
            model_name='bgeparticipanttrainingreport',
            name='bge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_training_reports', to='portfolio.businessgrowthexpert'),
        ),
    ]
