# Generated by Django 5.2.1 on 2026-08-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0090_add_bds_manual_module_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='msme',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude of business premises (decimal degrees)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='msme',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude of business premises (decimal degrees)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='visit_gps_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in metres at time of capture', null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='visit_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude captured when the report was filed', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='visit_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude captured when the report was filed', max_digits=9, null=True),
        ),
    ]
