# Generated by Django 5.2.1 on 2026-08-15 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0094_fix_jacob_odur_bge_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgeparticipanttrainingreport',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_reports', to='portfolio.trainingsession'),
        ),
    ]
