# Generated by Django 5.2.1 on 2026-08-22 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0098_smart_sync_al_maghtas_and_bge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupreport',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupreport',
            name='payment_confirmed_by_bge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupreport',
            name='payment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='groupreport',
            name='payment_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupreport',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Requisition/voucher or batch reference', max_length=150),
        ),
        migrations.AddField(
            model_name='groupreport',
            name='payment_status',
            field=models.CharField(choices=[('unsubmitted', 'Unsubmitted'), ('submitted', 'Submitted for Payment'), ('paid', 'Paid'), ('confirmed', 'Payment Confirmed by BGE')], default='unsubmitted', max_length=20),
        ),
        migrations.AddField(
            model_name='groupreport',
            name='payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupreport',
            name='payment_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_group_reports_for_payment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='payment_confirmed_by_bge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='payment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='payment_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Requisition/voucher or batch reference', max_length=150),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='payment_status',
            field=models.CharField(choices=[('unsubmitted', 'Unsubmitted'), ('submitted', 'Submitted for Payment'), ('paid', 'Paid'), ('confirmed', 'Payment Confirmed by BGE')], default='unsubmitted', max_length=20),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='payment_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_msme_reports_for_payment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='payment_confirmed_by_bge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Voucher, batch or invoice reference', max_length=150),
        ),
        migrations.AddField(
            model_name='workorder',
            name='payment_status',
            field=models.CharField(choices=[('pending_submission', 'Pending Submission'), ('submitted_for_payment', 'Submitted for Payment'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('payment_confirmed', 'Payment Confirmed by BGE')], default='pending_submission', max_length=30),
        ),
        migrations.AddField(
            model_name='workorder',
            name='payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='payment_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_work_orders_for_payment', to=settings.AUTH_USER_MODEL),
        ),
    ]
