# Generated by Django 5.2.1 on 2026-08-25 16:23

from django.db import migrations, models


def backfill_districts(apps, schema_editor):
    MSME = apps.get_model('portfolio', 'MSME')
    for m in MSME.objects.all():
        if m.state and not m.district:
            m.district = m.state
            m.save(update_fields=['district'])


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0101_add_msme_and_bge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='msme',
            name='alt_contact_name',
            field=models.CharField(blank=True, help_text='Alternative contact person name', max_length=100),
        ),
        migrations.AddField(
            model_name='msme',
            name='alt_contact_role',
            field=models.CharField(blank=True, help_text='Role/relationship of alternative contact (e.g. Manager, Caretaker, Spouse, Accountant)', max_length=100),
        ),
        migrations.AddField(
            model_name='msme',
            name='alt_email',
            field=models.EmailField(blank=True, help_text='Alternative contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='msme',
            name='alt_phone',
            field=models.CharField(blank=True, help_text='Alternative contact phone number', max_length=100),
        ),
        migrations.AddField(
            model_name='msme',
            name='district',
            field=models.CharField(blank=True, help_text='District where the MSME is located', max_length=100),
        ),
        migrations.RunPython(backfill_districts, migrations.RunPython.noop),
    ]

