# Generated by Django 5.2.1 on 2026-09-02 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0102_msme_alt_contact_name_msme_alt_contact_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('visit_type', models.CharField(choices=[('data_update', 'Data Collection Visit'), ('one_on_one', 'One-on-One Visit'), ('training', 'Training Visit'), ('coaching', 'Business Coaching Visit'), ('annual_review', 'Annual Review'), ('initial', 'Initial Assessment'), ('followup', 'Follow-up Visit'), ('final', 'Final Assessment'), ('mentoring', 'Mentoring Session'), ('quarterly_review', 'Quarterly Review')], default='one_on_one', max_length=30)),
                ('title', models.CharField(blank=True, help_text='Meeting title or focus area', max_length=255)),
                ('objectives', models.TextField(blank=True, help_text='Specific goals/outcomes planned for this session')),
                ('agenda', models.TextField(blank=True, help_text='Discussion points or BDS topics')),
                ('meeting_venue', models.CharField(choices=[('msme_premises', 'MSME Business Premises'), ('farm_site', 'Farm / Field / Production Site'), ('bge_base', 'BGE Field Base / District Office'), ('trading_center', 'Trading Centre / Neutral Venue'), ('virtual', 'Phone Call / Virtual Meeting'), ('other', 'Other Venue')], default='msme_premises', max_length=50)),
                ('meeting_venue_notes', models.CharField(blank=True, help_text='Specific venue address or landmark', max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True, help_text='General or preparation notes')),
                ('status', models.CharField(choices=[('planned', 'Planned Meeting'), ('completed', 'Completed'), ('missed', 'Missed'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=20)),
                ('missed_reason', models.CharField(blank=True, choices=[('msme_unavailable', 'MSME Owner / Contact Unavailable'), ('msme_closed', 'Business Premises Closed / Relocated'), ('bge_emergency', 'BGE Illness / Personal Emergency'), ('transport_logistics', 'Transport / Road Impassable / Breakdown'), ('weather', 'Adverse Weather / Heavy Rain / Floods'), ('rescheduled_msme', 'Rescheduled at MSME Request'), ('rescheduled_bge', 'Rescheduled by BGE'), ('security', 'Safety / Security Concern in Area'), ('other', 'Other Reason (see notes)')], default='', help_text='Standardized reason why the visit could not take place', max_length=50)),
                ('missed_reason_notes', models.TextField(blank=True, default='', help_text='Detailed narrative notes explaining the missed meeting circumstances')),
                ('missed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True, default='')),
                ('original_date', models.DateField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_visits', to='portfolio.businessgrowthexpert')),
                ('completed_report', models.ForeignKey(blank=True, help_text='Linked visit report filed on site', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_visits', to='portfolio.msmereport')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_planned_visits', to=settings.AUTH_USER_MODEL)),
                ('missed_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_missed_visits', to=settings.AUTH_USER_MODEL)),
                ('msme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_visits', to='portfolio.msme')),
                ('rescheduled_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_from', to='portfolio.plannedvisit')),
            ],
            options={
                'verbose_name': 'Planned Visit',
                'verbose_name_plural': 'Planned Visits',
                'ordering': ['scheduled_date', 'start_time', 'id'],
            },
        ),
    ]
