# Generated by Django 5.2.1 on 2026-09-03 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0104_plannedvisit_google_event_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BGEFieldPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='bge_photos/')),
                ('photo_data', models.BinaryField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('premises', 'MSME Premises / Shop / Facility'), ('products', 'Products / Produce / Inventory'), ('training', 'Training / Workshop Activity'), ('coaching', 'One-on-One Coaching Session'), ('attendance', 'Attendance Sheet / Physical Sign-in'), ('general', 'General Field Documentation')], default='general', max_length=30)),
                ('drive_file_id', models.CharField(blank=True, max_length=255)),
                ('drive_web_link', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_photos', to='portfolio.businessgrowthexpert')),
                ('msme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_photos', to='portfolio.msme')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_bge_photos', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_photos', to='portfolio.workorder')),
            ],
            options={
                'verbose_name': 'BGE Field Photo',
                'verbose_name_plural': 'BGE Field Photos',
                'ordering': ['-created_at'],
            },
        ),
    ]
