# Generated by Django 5.2.1 on 2026-09-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0105_bgefieldphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='msmereport',
            name='advice_delivered',
            field=models.TextField(blank=True, help_text='Immediate practical advice, demonstration, or coaching delivered on the spot (Diagnose & Advise)'),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='concrete_takeaway',
            field=models.TextField(blank=True, help_text='One concrete thing the MSME now knows to do differently starting today (The Acid Test)'),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='msme_visible_next_step',
            field=models.TextField(blank=True, help_text='Visible next step agreed with the MSME before departure (Mutual commitment)'),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='sms_summary_sent',
            field=models.BooleanField(default=False, help_text='Whether an SMS summary of the agreed action was sent to the MSME owner'),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='sms_summary_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msmereport',
            name='stated_purpose',
            field=models.TextField(blank=True, help_text='Stated purpose agreed with MSME owner upon opening the visit (Why we are here today)'),
        ),
    ]
