# Generated by Django 5.2.1 on 2026-09-07 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0108_alter_workorder_work_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='supported_bge',
            field=models.ForeignKey(
                blank=True,
                help_text='Primary BGE being supported in this technical co-assignment',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='supported_by_work_orders',
                to='portfolio.businessgrowthexpert',
            ),
        ),
        migrations.AddField(
            model_name='workorder',
            name='technical_area',
            field=models.CharField(
                blank=True,
                help_text='Area of greatest technical capacity for this co-assignment',
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_order_type',
            field=models.CharField(
                choices=[
                    ('permanent_assignee_support', 'Permanent Assignee Support (3x/Month) — Thematic Enterprise Coaching'),
                    ('msme_support', 'MSME CRM & Business Support'),
                    ('msme_data_update', 'MSME Data Update & Verification'),
                    ('msme_finance_survey', 'MSME Finance Survey (Google Forms)'),
                    ('msme_access_finance', 'Access to Finance & Digital Onboarding'),
                    ('access_to_finance_bge', 'Access to Finance — BGE Template'),
                    ('agro_biz_continuity', 'Agro-processors — Business Continuity & Strategic Planning'),
                    ('bcp_senior_facilitator', 'Agro-processors BCP — Senior BGE Lead Facilitator'),
                    ('mobilisation', 'Mobilisation / Outreach'),
                    ('group_session', 'Peer-to-Peer Group Session'),
                    ('bcp_tool_training', 'BCP Tool Training — BGE Participant'),
                    ('bge_bcp_participant_mentor', 'Agro-processors — Business Continuity & Strategic Planning (BGE Support)'),
                    ('outcome_assessment_tool', 'Outcome Assessment Tool Delivery'),
                    ('fi_mobilisation_bcp', 'BCP Tool - Field Implementation'),
                    ('carbon_emissions_training', 'Carbon Emissions Measurement Framework — Training & Field Implementation'),
                    ('csa_rapid_assessment', 'CSA Rapid Assessment — Resilience Activity'),
                    ('bds_manual_module', 'BDS Manual — Additional Module'),
                    ('bge_technical_co_assignment', 'BGE Technical Co-Assignment Support (Specialist Technical Capacity)'),
                    ('other', 'Other'),
                ],
                default='msme_support',
                max_length=40,
            ),
        ),
    ]
