# Generated by Django 5.2.1 on 2026-09-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0109_add_bge_technical_co_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msmereport',
            name='visit_type',
            field=models.CharField(choices=[('data_update', 'Data Collection Visit'), ('one_on_one', 'One-on-One Visit'), ('training', 'Training Visit'), ('coaching', 'Business Coaching Visit'), ('annual_review', 'Annual Review'), ('bcp_facilitation', 'BCP Facilitation & Accountability'), ('initial', 'Initial Assessment'), ('followup', 'Follow-up Visit'), ('final', 'Final Assessment'), ('mentoring', 'Mentoring Session'), ('quarterly_review', 'Quarterly Review')], default='followup', max_length=20),
        ),
        migrations.AlterField(
            model_name='plannedvisit',
            name='visit_type',
            field=models.CharField(choices=[('data_update', 'Data Collection Visit'), ('one_on_one', 'One-on-One Visit'), ('training', 'Training Visit'), ('coaching', 'Business Coaching Visit'), ('annual_review', 'Annual Review'), ('bcp_facilitation', 'BCP Facilitation & Accountability'), ('initial', 'Initial Assessment'), ('followup', 'Follow-up Visit'), ('final', 'Final Assessment'), ('mentoring', 'Mentoring Session'), ('quarterly_review', 'Quarterly Review')], default='one_on_one', max_length=30),
        ),
    ]
