# Generated by Django 5.2.1 on 2026-09-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0110_alter_msmereport_visit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msmereport',
            name='coaching_focus_area',
            field=models.CharField(blank=True, help_text='Focus areas for coaching or BCP visits', max_length=255),
        ),
    ]
