# Generated by Django 5.2.1 on 2026-09-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0111_alter_msmereport_coaching_focus_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msmereport',
            options={'ordering': ['-visit_date', '-created_at', '-id'], 'verbose_name': 'MSME Report'},
        ),
    ]
