# Generated by Django 5.2.1 on 2026-09-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0118_reassign_mobilisation_and_add_bankable_participant_wos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msmereport',
            name='coaching_focus_area',
            field=models.TextField(blank=True, help_text='Focus areas for coaching or BCP visits'),
        ),
    ]
