# Generated by Django 5.2.1 on 2026-09-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0120_enterprise_improvement_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='msme',
            name='diag_capacity_needs',
            field=models.JSONField(blank=True, default=list, help_text='List of requested capacity development areas'),
        ),
        migrations.AddField(
            model_name='msme',
            name='diag_digitalization_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Level of digitalization on a scale of 1 to 5', null=True),
        ),
        migrations.AddField(
            model_name='msme',
            name='diag_employees_ft_youth',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Full-time youth employees at diagnostic baseline', null=True),
        ),
        migrations.AddField(
            model_name='msme',
            name='diag_employees_pt_total',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Total part-time / casual employees at diagnostic baseline', null=True),
        ),
        migrations.AddField(
            model_name='msme',
            name='diag_monthly_profit',
            field=models.CharField(blank=True, help_text='Average monthly profit reported in diagnostic tool', max_length=100),
        ),
        migrations.AddField(
            model_name='msme',
            name='diag_profit_status',
            field=models.CharField(blank=True, help_text='Profitability status (Yes/No/Break-even)', max_length=50),
        ),
        migrations.AddField(
            model_name='msme',
            name='diagnostic_data',
            field=models.JSONField(blank=True, default=dict, help_text='Full 181-indicator survey responses dictionary'),
        ),
        migrations.AddField(
            model_name='msmegrowthsnapshot',
            name='digitalization_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Level of digitalization on a scale of 1 to 5', null=True),
        ),
        migrations.AddField(
            model_name='msmegrowthsnapshot',
            name='employees_ft_youth',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msmegrowthsnapshot',
            name='has_unbs',
            field=models.BooleanField(blank=True, help_text='Has UNBS certification or product standard', null=True),
        ),
    ]
