# Generated by Django 5.2.1 on 2026-09-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0122_seed_diagnostic_baselines'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseimprovementplan',
            name='help_needed_areas',
            field=models.JSONField(blank=True, default=list, help_text='List of assessment areas the MSME needs help with'),
        ),
        migrations.AddField(
            model_name='enterpriseimprovementplan',
            name='help_needed_description',
            field=models.TextField(blank=True, help_text='Detailed description of specific help/BDS support needed by MSME'),
        ),
    ]
